Repository Ericsson/CodeCompass, pull requests merged in 2018-11, with the labels that each got.

#274 Refactored file diagrams to generate directory level relations on-demand
  model/include/model/file.h
  plugins/cpp/model/CMakeLists.txt
  plugins/cpp/model/include/model/cppedge.h
  plugins/cpp/model/include/model/cppnode.h
  plugins/cpp/parser/include/cppparser/cppparser.h
  plugins/cpp/parser/src/cppparser.cpp
  plugins/cpp/parser/src/relationcollector.cpp
  plugins/cpp/parser/src/relationcollector.h
  plugins/cpp/service/src/filediagram.cpp
  plugins/cpp/service/src/filediagram.h
Labels: Kind: Enhancement, Target: C++, Target: Visualisation

#257 Enhance test project and fix C++ test expectations
  .gitignore
  CMakeLists.txt
  Functions.cmake
  Testing.cmake
  doc/deps.md
  plugins/cpp/test/CMakeLists.txt
  plugins/cpp/test/sources/CMakeLists.txt
  plugins/cpp/test/src/cppreferenceservicetest.cpp
  plugins/cpp/test/src/cppservicetest.cpp
Labels: Kind: Enhancement, Kind: Refactor, Target: Developer environment, Target: Test

#300 Fixed erasure bug in getImplementedFiles and getDependFiles.
  plugins/cpp/service/src/filediagram.cpp
Labels: Kind: Bug, Target: C++
