Repository Ericsson/CodeCompass, pull requests merged in 2018-09, with the labels that each got.

#266 Incremental parsing
  .gitignore
  doc/usage.md
  model/include/model/buildlog.h
  model/include/model/buildsourcetarget.h
  model/include/model/fileloc.h
  parser/CMakeLists.txt
  parser/include/parser/abstractparser.h
  parser/include/parser/parsercontext.h
  parser/include/parser/sourcemanager.h
  parser/src/parser.cpp
  parser/src/parsercontext.cpp
  parser/src/sourcemanager.cpp
  plugins/cpp/model/include/model/cppedge.h
  plugins/cpp/model/include/model/cppfunction.h
  plugins/cpp/model/include/model/cppheaderinclusion.h
  plugins/cpp/model/include/model/cppnode.h
  plugins/cpp/model/include/model/cpptype.h
  plugins/cpp/parser/include/cppparser/cppparser.h
  plugins/cpp/parser/src/cppparser.cpp
  plugins/cpp/test/src/cpppropertiesservicetest.cpp
  plugins/cpp/test/src/cppreferenceservicetest.cpp
  plugins/metrics/parser/include/metricsparser/metricsparser.h
  plugins/metrics/parser/src/metricsparser.cpp
  plugins/search/parser/src/searchparser.cpp
  util/include/util/dbutil.h
  util/src/dbutil.cpp
  webserver/include/webserver/pluginhelper.h
Labels: Kind: Enhancement, Kind: Support, Target: C++, Target: Database

#279 LC_CTYPE has to be given at database creation.
  util/src/dbutil.cpp
Labels: Kind: Enhancement, Kind: Support, Target: Database

#285 Use the automatic mirror selector for Thrift as opposed to SOTE
  doc/deps.md
Labels: Kind: Enhancement, Target: Developer environment, Target: Documentation
