Repository Ericsson/CodeCompass, pull requests merged in 2018-05, with the labels that each got.

#242 Fix 'corethriftjava' failing to build when JAR is compiled earlier than Thrift generation
  plugins/dummy/service/CMakeLists.txt
  plugins/git/service/CMakeLists.txt
  plugins/metrics/service/CMakeLists.txt
  plugins/search/indexer/CMakeLists.txt
  plugins/search/service/CMakeLists.txt
  service/language/CMakeLists.txt
  service/plugin/CMakeLists.txt
  service/project/CMakeLists.txt
  service/workspace/CMakeLists.txt
Labels: Kind: Bug

#244 Fix typo of thriftfile name in CMake output
  service/plugin/CMakeLists.txt
Labels: Kind: Refactor, Target: Developer environment

#245 Massively speed up navigation by not sending source text for every AST node
  plugins/cpp/service/include/service/cppservice.h
  plugins/cpp/service/src/cppservice.cpp
  service/language/language.thrift
  webgui/scripts/codecompass/view/codeBites.js
Labels: Kind: Bug, Taget: C++

#256 Update usage guide
  doc/coding_conventions.md
  doc/usage.md
Labels: Kind: Enhancement, Target: Documentation

#258 Fix CREATE USER command for PostgreSQL.
  doc/usage.md
Labels: Kind: Bug, Target: Documentation
