Repository Ericsson/CodeCompass, pull requests merged in 2018-07, with the labels that each got.

#263 Enhancements to automate finding of paths in installed environment
  CMakeLists.txt
  Config.cmake
  Exports.cmake
  FindThrift.cmake
  Functions.cmake
  doc/usage.md
  parser/include/parser/parsercontext.h
  parser/src/parser.cpp
  plugins/cpp/service/include/service/cppservice.h
  plugins/cpp/service/src/cppservice.cpp
  plugins/cpp/service/src/diagram.cpp
  plugins/cpp/service/src/diagram.h
  plugins/cpp/service/src/filediagram.cpp
  plugins/cpp/service/src/filediagram.h
  plugins/cpp/service/src/plugin.cpp
  plugins/cpp/test/src/cpppropertiesservicetest.cpp
  plugins/cpp/test/src/cppreferenceservicetest.cpp
  plugins/dummy/service/CMakeLists.txt
  plugins/dummy/service/include/service/dummyservice.h
  plugins/dummy/service/src/dummyservice.cpp
  plugins/dummy/service/src/plugin.cpp
  plugins/git/service/CMakeLists.txt
  plugins/git/service/include/service/gitservice.h
  plugins/git/service/src/gitservice.cpp
  plugins/git/service/src/plugin.cpp
  plugins/metrics/service/CMakeLists.txt
  plugins/metrics/service/include/metricsservice/metricsservice.h
  plugins/metrics/service/src/metricsservice.cpp
  plugins/metrics/service/src/plugin.cpp
  plugins/search/indexer/CMakeLists.txt
  plugins/search/indexer/include/indexer/indexerprocess.h
  plugins/search/indexer/src/indexerprocess.cpp
  plugins/search/parser/src/searchparser.cpp
  plugins/search/service/CMakeLists.txt
  plugins/search/service/include/service/searchservice.h
  plugins/search/service/include/service/serviceprocess.h
  plugins/search/service/src/plugin.cpp
  plugins/search/service/src/searchservice.cpp
  scripts/CMakeLists.txt
  scripts/keepalive
  service/language/CMakeLists.txt
  service/plugin/CMakeLists.txt
  service/plugin/include/pluginservice/pluginservice.h
  service/plugin/src/plugin.cpp
  service/plugin/src/pluginservice.cpp
  service/project/CMakeLists.txt
  service/project/include/projectservice/projectservice.h
  service/project/src/plugin.cpp
  service/project/src/projectservice.cpp
  service/workspace/CMakeLists.txt
  service/workspace/src/plugin.cpp
  util/CMakeLists.txt
  util/include/util/filesystem.h
  util/src/filesystem.cpp
  webserver/include/webserver/pluginhandler.h
  webserver/include/webserver/pluginhelper.h
  webserver/include/webserver/servercontext.h
  webserver/src/webserver.cpp
Labels: Kind: Enhancement, Kind: Support, Target: Developer environment

#262 Update the dependency guide to contain details for Ubuntu 18.04 LTS
  doc/deps.md
Labels: Target: Developer environment, Target: Documentation

#261 Do not depend on libsqlite3 being installed if PostgreSQL database is used
  FindOdb.cmake
  doc/deps.md
  util/CMakeLists.txt
  util/include/util/odbtransaction.h
Labels: Kind: Bug, Target: Developer environment

#251 Eliminate unused field, argument, and some more warnings
  plugins/cpp/parser/src/cppparser.cpp
  plugins/cpp/parser/src/relationcollector.cpp
  plugins/cpp/parser/src/relationcollector.h
  plugins/cpp/service/include/service/cppservice.h
  plugins/cpp/service/src/cppservice.cpp
  plugins/git/service/include/service/gitservice.h
  plugins/metrics/service/include/metricsservice/metricsservice.h
  plugins/metrics/service/src/metricsservice.cpp
Labels: Kind: Refactor, Target: Developer environment

#265 Fix non-compiling code
  plugins/git/service/src/gitservice.cpp
  plugins/metrics/service/src/metricsservice.cpp
Labels: Kind: Critical
