Repository Ericsson/CodeCompass, pull requests merged in 2019-10, with the labels that each got.

#347 Added queries for provided files for include dependency diagram.
  .travis.yml
  plugins/cpp/service/src/filediagram.cpp
Labels: Kind: Bug, Target: Visualisation

#349 Docker image for CodeCompass build environment
  README.md
  doc/deps.md
  scripts/docker/Dockerfile
  scripts/docker/codecompass-build.sh
Labels: Discussion

#351 Force javac to handle source files encoded in utf-8
  CMakeLists.txt
Labels: Kind: Bug, Target: Java

#352 Fixing wildcard search with Lucene
  plugins/search/lib/java/lucene-memory-4.9.0.jar
Labels: Kind: Bug
