Repository Ericsson/CodeCompass, pull requests merged in 2019-05, with the labels that each got.

#323 Generate .sql files into the build directory
  Config.cmake
  Functions.cmake
  model/CMakeLists.txt
  plugins/cpp/model/CMakeLists.txt
  plugins/metrics/model/CMakeLists.txt
  plugins/search/parser/CMakeLists.txt
Labels: Kind: Bug, Target: Developer environment

#330 ODB known issues in the documentation.
  doc/deps.md
Labels: Target: Documentation

#329 Case-sensitive LIKE in SQLite
  util/src/dbutil.cpp
Labels: Kind: Bug, Target: Database

#327 Add Travis CI
  .travis.yml
  CMakeLists.txt
Labels: Target: Developer environment

#331 Add recommended dependencies explicitly
  doc/deps.md
Labels: Discussion, Target: Documentation
