Repository Ericsson/CodeCompass, pull requests merged in 2019-11, with the labels that each got.

#355 Refactoring docker image for development
  scripts/docker/Dockerfile
  scripts/docker/codecompass-build.sh
Labels: Kind: Bug, Kind: Enhancement

#72 Cpp syntax highlight
  plugins/cpp/service/include/service/cppservice.h
  plugins/cpp/service/src/cppservice.cpp
  service/language/language.thrift
  webgui/scripts/codecompass/view/component/Text.js
  webgui/style/codecompass.css
Labels: Kind: Enhancement

#361 Fix docker run command in the documentation
  docker/README.md
Labels: Kind: Bug, Target: Documentation

#362 Eliminating parser dependencies
  parser/include/parser/abstractparser.h
  parser/include/parser/pluginhandler.h
  parser/src/parser.cpp
  parser/src/pluginhandler.cpp
  plugins/cpp/parser/include/cppparser/cppparser.h
  plugins/cpp/parser/src/cppparser.cpp
  plugins/dummy/parser/include/dummyparser/dummyparser.h
  plugins/dummy/parser/src/dummyparser.cpp
  plugins/git/parser/include/gitparser/gitparser.h
  plugins/git/parser/src/gitparser.cpp
  plugins/metrics/parser/include/metricsparser/metricsparser.h
  plugins/metrics/parser/src/metricsparser.cpp
  plugins/search/parser/include/searchparser/searchparser.h
  plugins/search/parser/src/searchparser.cpp
Labels: Kind: Refactor

#363 Error when running CodeCompass binary from extended PATH
  util/src/filesystem.cpp
Labels: Kind: Bug

#364 Find git2 package instead of git
  plugins/CMakeLists.txt
  plugins/git/CMakeLists.txt
  plugins/git/FindGit2.cmake
Labels: Kind: Bug

#359 [server] Remove database option from webserver
  doc/usage.md
  docker/README.md
  parser/src/parser.cpp
  webserver/include/webserver/pluginhelper.h
  webserver/src/webserver.cpp
Labels: Kind: Refactor

#365 keepalive is not needed
  doc/usage.md
  scripts/CMakeLists.txt
  scripts/keepalive
Labels: Kind: Enhancement, Target: Documentation
