Repository Ericsson/CodeCompass, pull requests merged in 2019-04, with the labels that each got.

#320 Fixup createOdbOptions() usage
  util/src/dbutil.cpp
Labels: Kind: Bug, Kind: Critical, Target: Database

#282 User shouldn't create DB manually
  doc/usage.md
Labels: Target: Documentation

#322 Do not use keepalive in tests
  plugins/cpp/test/CMakeLists.txt
Labels: Target: Test

#236 Fixing ubuntu packaged LLVM compilation
  plugins/cpp/parser/CMakeLists.txt
  plugins/cpp_reparse/service/CMakeLists.txt
Labels: Kind: Question, Kind: Support

#325 Error message instead of turning dry-run off
  parser/src/parser.cpp
Labels: Kind: Bug
