Repository Ericsson/CodeCompass, pull requests merged in 2019-03, with the labels that each got.

#315 Better connection string handling
  parser/src/parser.cpp
  util/include/util/dbutil.h
  util/src/dbutil.cpp
Labels: Kind: Enhancement

#316 Google Testing installation
  doc/deps.md
Labels: Target: Documentation

#310 Cpp parser test
  plugins/cpp/model/CMakeLists.txt
  plugins/cpp/model/include/model/cppastnode.h
  plugins/cpp/parser/src/clangastvisitor.h
  plugins/cpp/test/CMakeLists.txt
  plugins/cpp/test/sources/parser/CMakeLists.txt
  plugins/cpp/test/sources/parser/cxxrecord.cpp
  plugins/cpp/test/sources/parser/enum.cpp
  plugins/cpp/test/sources/parser/function.cpp
  plugins/cpp/test/sources/parser/namespace.cpp
  plugins/cpp/test/sources/parser/typedef.cpp
  plugins/cpp/test/sources/parser/variable.cpp
  plugins/cpp/test/sources/service/CMakeLists.txt
  plugins/cpp/test/sources/service/inheritance.cpp
  plugins/cpp/test/sources/service/inheritance.h
  plugins/cpp/test/sources/service/nestedclass.cpp
  plugins/cpp/test/sources/service/nestedclass.h
  plugins/cpp/test/sources/service/simpleclass.cpp
  plugins/cpp/test/sources/service/simpleclass.h
  plugins/cpp/test/src/cppparsertest.cpp
  plugins/cpp/test/src/cpptest.cpp
Labels: Target: C++, Target: Test
