Repository Ericsson/CodeCompass, pull requests merged in 2020-10, with the labels that each got.

#474 Add CI test for parsing CodeCompass itself
  .travis.yml
Labels: Target: Developer environment, Target: Test

#473 Lower required CMake version to 3.5.1
  CMakeLists.txt
  Functions.cmake
  webgui/InstallGUI.cmake
Labels: Kind: Refactor, Target: Developer environment

#448 Excluding node sort at function parameters.
  plugins/cpp/service/src/cppservice.cpp
Labels: Kind: Bug, Target: WebGUI

#429 Usr
  plugins/cpp/model/include/model/cppastnode.h
  plugins/cpp/model/include/model/cppdoccomment.h
  plugins/cpp/model/include/model/cppentity.h
  plugins/cpp/model/include/model/cppenum.h
  plugins/cpp/model/include/model/cppfunction.h
  plugins/cpp/model/include/model/cppmacro.h
  plugins/cpp/model/include/model/cppnamespace.h
  plugins/cpp/model/include/model/cpprecord.h
  plugins/cpp/model/include/model/cpptypedef.h
  plugins/cpp/model/include/model/cppvariable.h
  plugins/cpp/parser/CMakeLists.txt
  plugins/cpp/parser/src/clangastvisitor.h
  plugins/cpp/parser/src/cppparser.cpp
  plugins/cpp/parser/src/doccommentcollector.h
  plugins/cpp/parser/src/entitycache.cpp
  plugins/cpp/parser/src/entitycache.h
  plugins/cpp/parser/src/manglednamecache.cpp
  plugins/cpp/parser/src/ppincludecallback.cpp
  plugins/cpp/parser/src/ppincludecallback.h
  plugins/cpp/parser/src/ppmacrocallback.cpp
  plugins/cpp/parser/src/ppmacrocallback.h
  plugins/cpp/parser/src/symbolhelper.cpp
  plugins/cpp/parser/src/symbolhelper.h
  plugins/cpp/service/include/service/cppservice.h
  plugins/cpp/service/src/cppservice.cpp
  plugins/cpp/test/src/cppparsertest.cpp
  plugins/cpp/webgui/js/cppInfoTree.js
  service/language/language.thrift
  webserver/include/webserver/thrifthandler.h
Labels: Kind: Enhancement, Plugin: C++

#479 Travis CI: Switch to minimal image
  .travis.yml
Labels: Target: Developer environment

#481 Cover the case of CXXDeductionGuideDecl
  plugins/cpp/parser/src/clangastvisitor.h
Labels: Kind: Bug, Plugin: C++

#482 Typo fix in C++ parser CXXDeductionGuideDecl
  plugins/cpp/parser/src/clangastvisitor.h
Labels: Kind: Bug, Plugin: C++

#484 Set RelWithDebInfo as default build type
  Config.cmake
  doc/deps.md
Labels: Target: Developer environment

#480 Test parsing of TinyXML2 and Xerces-C++ projects in the CI
  .travis.yml
Labels: Target: Developer environment

#486 Do not check for virtual tag on FunctionPtr definitions
  plugins/cpp/service/src/cppservice.cpp
Labels: Kind: Bug, Plugin: C++
