Repository Ericsson/CodeCompass, pull requests merged in 2020-05, with the labels that each got.

#387 Wire in SSL certificate support
  doc/usage.md
  service/workspace/src/workspaceservice.cpp
  webserver/CMakeLists.txt
  webserver/src/webserver.cpp
Labels: Kind: Enhancement, Kind: Important

#386 Implement requiring authentication to access a server
  Config.cmake
  doc/authentication.md
  service/CMakeLists.txt
  service/authentication/CMakeLists.txt
  service/authentication/authentication.thrift
  service/authentication/include/authenticationservice/authenticationservice.h
  service/authentication/src/authenticationservice.cpp
  service/authentication/src/plugin.cpp
  webgui/CMakeLists.txt
  webgui/index.html
  webgui/login.html
  webgui/scripts/codecompass/model.js
  webgui/scripts/codecompass/view/header.js
  webgui/scripts/login/MessagePane.js
  webgui/scripts/login/login.js
  webgui/style/login.css
  webserver/CMakeLists.txt
  webserver/authenticators/CMakeLists.txt
  webserver/authenticators/plain/CMakeLists.txt
  webserver/authenticators/plain/src/plugin.cpp
  webserver/include/webserver/authenticator.h
  webserver/include/webserver/pluginhandler.h
  webserver/include/webserver/requesthandler.h
  webserver/include/webserver/servercontext.h
  webserver/include/webserver/session.h
  webserver/include/webserver/thrifthandler.h
  webserver/src/authentication.cpp
  webserver/src/authentication.h
  webserver/src/mainrequesthandler.cpp
  webserver/src/mainrequesthandler.h
  webserver/src/mongoose.c
  webserver/src/session.cpp
  webserver/src/sessionmanager.cpp
  webserver/src/sessionmanager.h
  webserver/src/webserver.cpp
Labels: Kind: Enhancement, Kind: Important

#391 Show diagram legend for directories
  plugins/cpp/service/src/cppservice.cpp
Labels: Kind: Bug

#385 Switched to odb 2.5 from 2.4, since the version 2.4 is currently broken.
  .travis.yml
  FindOdb.cmake
  Functions.cmake
  doc/deps.md
  doc/usage.md
  docker/README.md
  docker/dev/Dockerfile
  model/include/model/buildaction.h
  plugins/cpp/model/include/model/cppentity.h
Labels: Kind: Critical, Target: Developer environment, Target: Documentation

#354 Docker image to run CodeCompass webserver
  docker/README.md
  docker/dev/Dockerfile
  docker/web/Dockerfile
  docker/web/entrypoint.sh
Labels: Kind: Enhancement
