Repository Ericsson/CodeCompass, pull requests merged in 2020-07, with the labels that each got.

#393 Guide and update for Ubuntu 20.04
  .travis.yml
  Functions.cmake
  doc/deps.md
  plugins/cpp_reparse/service/CMakeLists.txt
  plugins/git/service/git.thrift
  plugins/git/service/src/gitservice.cpp
  plugins/git/webgui/js/gitNavigator.js
  util/include/util/hash.h
Labels: Kind: Support, Target: Developer environment, Target: Documentation

#406 I read throught the docs, and fixed some typos.
  doc/coding_conventions.md
  doc/deps.md
  doc/usage.md
Labels: Kind: Enhancement, Target: Documentation

#398 Docker image upgrade to Ubuntu 20.04
  Functions.cmake
  docker/dev/Dockerfile
  docker/web/Dockerfile
  parser/CMakeLists.txt
  plugins/cpp/test/CMakeLists.txt
  plugins/metrics/parser/CMakeLists.txt
  plugins/search/indexer/CMakeLists.txt
  util/CMakeLists.txt
  webserver/CMakeLists.txt
Labels: Kind: Support, Target: Developer environment

#407 Link authentication guide into main usage guide
  doc/usage.md
Labels: Target: Documentation

#401 Left side and file content menu fix
  plugins/cpp/service/src/cppservice.cpp
  webgui/scripts/codecompass/view/component/Text.js
Labels: Kind: Bug

#411 Update Build2 version from 0.12.0 to 0.13.0
  .travis.yml
  doc/deps.md
Labels: Kind: Critical, Kind: Support, Target: Developer environment, Target: Documentation

#408 Modified the file manager menu to contain a menu item for git blame.
  plugins/git/webgui/js/gitMenu.js
Labels: Kind: Enhancement, Plugin: Git, Target: WebGUI

#410 Use PostgreSQL in Docker containers
  docker/dev/Dockerfile
  docker/web/Dockerfile
Labels: Kind: Bug, Kind: Support, Target: Developer environment

#403 Adding C++ compiler diagnostic messages to the database
  model/include/model/buildlog.h
  plugins/cpp/parser/CMakeLists.txt
  plugins/cpp/parser/include/cppparser/filelocutil.h
  plugins/cpp/parser/src/cppparser.cpp
  plugins/cpp/parser/src/diagnosticmessagehandler.cpp
  plugins/cpp/parser/src/diagnosticmessagehandler.h
Labels: Kind: Enhancement, Plugin: C++

#402 Use the Dojo Build System
  .gitignore
  service/plugin/include/pluginservice/pluginservice.h
  service/plugin/plugin.thrift
  service/plugin/src/pluginservice.cpp
  webgui/CMakeLists.txt
  webgui/InstallGUI.cmake
  webgui/codecompass.profile.js.in
  webgui/index.html
  webgui/login.html
  webgui/package.json
Labels: Kind: Enhancement, Kind: Refactor, Target: WebGUI
