Repository Ericsson/CodeCompass, pull requests merged in 2021-05, with the labels that each got.

#526 Google Analytics event tracking
  plugins/cpp/webgui/js/cppMenu.js
  plugins/cpp_reparse/webgui/js/cppReparseFileAST.js
  plugins/git/webgui/js/gitBlame.js
  plugins/metrics/webgui/js/metrics.js
  plugins/search/webgui/js/searchResult.js
  webgui/scripts/codecompass/view/codeBites.js
  webgui/scripts/codecompass/view/component/Text.js
  webgui/scripts/codecompass/view/diagram.js
Labels: Kind: Enhancement, Target: WebGUI

#531 Upgrade libthrift java library from 0.12.0 to 0.13.0
  lib/java/httpclient-4.5.6.jar
  lib/java/httpcore-4.4.10.jar
  lib/java/libthrift-0.12.0.jar
  lib/java/libthrift-0.13.0.jar
  plugins/search/common/src/cc/search/common/ipc/IPCProcessor.java
Labels: Kind: Bug

#511 Safer docker script approach
  docker/dev/Dockerfile
  docker/dev/codecompass-build.sh
Labels: Target: Developer environment

#525 Remove mentions and guides for Ubuntu 16.04 "Xenial Xerus"
  .travis.yml
  doc/deps.md
Labels: Kind: Support, Target: Developer environment, Target: Documentation

#524 Only the desired sql engine is installed into the container.
  docker/runtime/Dockerfile
Labels: Kind: Refactor, Target: Developer environment

#534 Handle symlinks in python parser.
  plugins/python/parser/src/scripts/cc_python_parser/file_info.py
  plugins/python/parser/src/scripts/cc_python_parser/parser.py
  plugins/python/parser/src/scripts/cc_python_parser/persistence/__init__.py
  plugins/python/parser/src/scripts/cc_python_parser/persistence/class_dto.py
Labels: Plugin: Python

#529 LDAP authentication
  .github/workflows/ci.yml
  FindOpenLdap.cmake
  doc/authentication.md
  doc/deps.md
  docker/dev/Dockerfile
  docker/runtime/Dockerfile
  docker/web/Dockerfile
  webserver/authenticators/CMakeLists.txt
  webserver/authenticators/ldap/CMakeLists.txt
  webserver/authenticators/ldap/ldap-cpp/cldap.h
  webserver/authenticators/ldap/ldap-cpp/cldap_entry.cpp
  webserver/authenticators/ldap/ldap-cpp/cldap_entry.h
  webserver/authenticators/ldap/ldap-cpp/cldap_mod.cpp
  webserver/authenticators/ldap/ldap-cpp/cldap_mod.h
  webserver/authenticators/ldap/ldap-cpp/cldap_server.cpp
  webserver/authenticators/ldap/ldap-cpp/cldap_server.h
  webserver/authenticators/ldap/ldap-cpp/cldap_types.h
  webserver/authenticators/ldap/src/plugin.cpp
Labels: Kind: Enhancement, Target: Authentication
