Repository Ericsson/CodeCompass, pull requests merged in 2021-01, with the labels that each got.

#502 CallExpr can be applied to a function pointer
  plugins/cpp/parser/src/clangastvisitor.h
  plugins/cpp/service/src/cppservice.cpp
Labels: Kind: Bug, Kind: Refactor, Plugin: C++

#501 Rename cacheFiles() function to reloadCache()
  parser/include/parser/sourcemanager.h
  parser/src/parser.cpp
  parser/src/sourcemanager.cpp
Labels: Kind: Refactor

#503 Github Actions jobs
  .github/workflows/ci.yml
Labels: Kind: Enhancement, Kind: Important, Target: Developer environment
