Repository Ericsson/CodeCompass, pull requests merged in 2022-03, with the labels that each got.

#561 Archive artifacts before upload
  .github/workflows/ci.yml
Labels: Kind: Enhancement, Target: Developer environment

#563 Add .vscode to gitignore
  .gitignore
Labels: Target: Developer environment

#565 Complementing GA functions
  plugins/cpp/webgui/js/cppMenu.js
Labels: Kind: Enhancement, Target: Developer environment

#564 docs: add missing postgresql dependency and use apt everywhere
  doc/deps.md
  doc/usage.md
Labels: Target: Documentation
