Repository Ericsson/CodeCompass, pull requests merged in 2024-03, with the labels that each got.

#716 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: Target: Developer environment

#715 Adding Scorecard badge to the Readme.
  README.md
Labels: Target: Developer environment

#706 Update NextJs to v14.1 for new frontend
  doc/deps.md
  webgui-new/.nvmrc
  webgui-new/README.md
  webgui-new/next.config.js
  webgui-new/package-lock.json
  webgui-new/package.json
Labels: Kind: Refactor :arrows_clockwise:, Target: Developer environment, Target: WebGUI

#717 Separate docker image build jobs
  .github/workflows/docker.yml
Labels: Kind: Refactor :arrows_clockwise:, Target: Developer environment

#719 CodeQL integration to CI
  .github/workflows/codeql.yml
Labels: Kind: Enhancement :star2:, Target: Developer environment
