Repository Ericsson/CodeCompass, pull requests merged in 2024-04, with the labels that each got.

#730 Update Scorecard Action version
  .github/workflows/scorecard.yml
Labels: Kind: Bug :warning:, Target: Developer environment

#737 chore: `wget` Build2 script instead of code view HTML
  doc/deps.md
Labels: Target: Documentation, Target: Developer environment

#724 Move CodeQL workflow permissions to the top level
  .github/workflows/codeql.yml
Labels: Target: Developer environment
